### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by little-george-cz** [fragsalat/rust-ccs811#1]
I'm a complete beginner but I  think I found a bug in chip.rs
121: .and(self.check_status(CCS811_STATUS_APP_MODE & CCS811_STATUS_APP_VERIFY))?;
it should be right
121: .and(self.check_status(CCS811_STATUS_APP_MODE | CCS811_STATUS_APP_VALID))?;

**Comment by fragsalat** [comment]
Hey @little-george-cz indeed this does make more sense to me. Which error did you get to recognize this bug? I'll fix this today.

**Comment by fragsalat** [comment]
I published the version 0.1.3. Could you please be so kind to test for me if it still works? I currently have my sensor misplaced.

**Comment by little-george-cz** [comment]
(I use GOOGLE translator, sorry)
Yes, it seems that everything is all right now. I don't know RUST at all. First of all, I needed to upgrade the firmware in my CCS811, which was also functional in the original version 0.1.2. I discovered this error because there is a substitution of the & a | operators in C as well is quite common in this case. Thank you.
